### PR TITLE
added the login and signup page

### PR DESCRIPTION
**Pull request by awsmdeep**

### CODE REVIEW

**Comment by awsmdeep** [comment]
@priyamaggarwal18 check the page once , i hope uu like the changes

**Comment by priyamaggarwal18** [comment]
The sign in to sign up animation is not smooth also choose a different image and give some hover CSS to buttons.

**Comment by awsmdeep** [comment]
@priyamaggarwal18 made all the corrections as you have asked , i hope uu like it

**Comment by priyamaggarwal18** [comment]
Can you ellaborate what changes you have made?

**Comment by awsmdeep** [comment]
Made the animation smooth and changed the image and added hover effect to the button

**Comment by priyamaggarwal18** [comment]
Keep form color white. Take care of CSS as it is now looking very bad.

Also, after you are done with CSS and add a Video to showcase how it looks in these comments only.

**Comment by awsmdeep** [comment]
Can you give the details how you want the login page

**Comment by awsmdeep** [comment]
I tried to keep the theme dark because the  color combination of the homepage is black and red

**Comment by priyamaggarwal18** [comment]
These are the things that you can do 
1. keep the background dark, but form color should be white.
2. also, on going from login to signup, the animation should be smooth. Not a black screen shifting from left to right or vice versa.

Rest is all on you. Do make changes and share a video in comments only.

**Comment by awsmdeep** [comment]
https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/89087538/8cc7922b-a6e9-41d8-8241-39e82b13476d

@priyamaggarwal18 shared the video of the changes made

**Pull request merged**
