### PR TITLE
feat: modified README.md

### PR DESCRIPTION
**Pull request by fracergu**

### CODE REVIEW

**Comment by fracergu** [comment]
@priyamaggarwal18 If you want to add more specific texts to some sections, feel free to suggest.

**Comment by priyamaggarwal18** [comment]
Maintainer code format should be same, you can add some emojis,  but the alignment should be perfect.

Also, please do add functional linked in introduction section if possible
one more thing, add a proper screenshot of the landing page, you can take reference from web link of webpage.

**Comment by fracergu** [comment]
@priyamaggarwal18 added suggested changes. 
- Change image to a raw screenshot of website
- Moved index to introduction section
- Restored old mantainer section
- Also added a bit more content on "Hactoberfest" and "How works" sections and merged "Contribute" and "Step-by-step" section into a single one to avoid redunancy.

**Comment by priyamaggarwal18** [comment]
These are the last changes that I want 

1. Add ⚡ emoji instead of 🛴.
2. In the photo, do add the navbar.
3. also add some assets of Hacktoberfest.

**Comment by fracergu** [comment]
@priyamaggarwal18 

Can you set a `hacktoberfest-accepted` label or make a review to the PR? I need it to count it into my hacktoberfest PRs. Thanks!

**Pull request merged**
