### PR TITLE
Enhanced the Login/Signup Page

### PR DESCRIPTION
**Pull request by kshitizvardhan**
# Pull Request : Enhancing Login/Signup Page  Issue Number- #10 

## Issue Resolved:
In this Pull request,  made significant enhancements to the Login/Signup page (Issue #10). The primary goal was to improve the user experience and styling of the page.

## Changes Made:
- Added Content on left side of the page with animations to be a dynamic login/signup page.
- Issue resolved: Changed Input type 'text' to 'password' for all password inputs.
- Added Labels on the remember me and agree terms checkboxes for better user experience.
- Hover Transitions on Submit button

## Before Screen Shot

Screenshot 2023-10-24 145127

## After Screen Shot and Video

Screenshot 2023-10-24 144814

https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/143323194/53eb3339-2a8a-4fe3-a9ac-fcb0e92f13a6

Resolved Issue No. #10

### CODE REVIEW

**Comment by priyamaggarwal18** [comment]
Make font white for buttons.
Make background in dark theme if possible.

In short, convert into dark theme.

**Comment by kshitizvardhan** [comment]
I will work on these changes and provide update to this pull request.

**Comment by kshitizvardhan** [comment]
## Changes Requested Are Done #12  

- Page is now in Dark Theme
- All buttons in white

### Here is the Video of the work Attached.
Screenshot 2023-10-24 165951


https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/143323194/535c6644-5716-4ead-9ad0-e96cdaf73ac9

**Comment by priyamaggarwal18** [comment]
Nice work

**Pull request merged**
