### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by harshvyas-22**
made a footer add links accordingly

### CODE REVIEW

**Comment by priyamaggarwal18** [comment]
can you attach a video.

**Comment by harshvyas-22** [comment]
https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/118657807/76634d46-41d5-43aa-bb19-8e05a096b642

**Comment by priyamaggarwal18** [comment]
CSS is not good , will you fix it

**Comment by harshvyas-22** [comment]
ok i will work on it

**Comment by harshvyas-22** [comment]
changed footbar

**Comment by harshvyas-22** [comment]
https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/118657807/fc00b8fe-8232-464c-9914-294ccb711b48

**Comment by harshvyas-22** [comment]
love to hear future modifications ,if you liked it please merge it

**Comment by Kartikey-Bartwal** [comment]
its good 👍

**Review by KartikeyBartwal — COMMENTED** [review]
the footer looks good and the code is clean

**Comment by harshvyas-22** [comment]
Please Merge it then

**Comment by kshitizvardhan** [comment]
@harshvyas-22  About section css and button css in many sections, not working as it was earlier.

**Comment by harshvyas-22** [comment]
Can i do it in the morning?  Assign this to me

**Comment by harshvyas-22** [comment]
https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/118657807/efc0250b-b7c4-419f-9065-081b2e35ede6

**Comment by priyamaggarwal18** [comment]
Great work, but need some changes
1. Keep CSS of button same as previous as login signup button, button on about page are not same.
2. Try to keep the hex code color red for buttons in footer.
3. also add some SVG for contact and mail. (take reference from remix icons).


After doing so, attach a video for the same.

**Comment by harshvyas-22** [comment]
https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/118657807/eac3218f-de98-4613-bde7-72339017ca39

**Comment by priyamaggarwal18** [comment]
better

**Comment by priyamaggarwal18** [comment]
#9 resolved

**Pull request merged**
