### PR TITLE
Added a Feature: Animations on HomePage

### PR DESCRIPTION
**Pull request by kshitizvardhan**
# Issue #6  : Solved Issue - Adding Animations on HomePage

### Description
This issue was opened to address the problem of missing animations on the homepage. The issue has been successfully resolved, and animations have been added to the homepage. Now the homepage looks more dynamic.

### Changes Made
- Added animations to the homepage.
- Verified that the animations are working correctly.

Resolved Issue: #6 

### Video

https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/143323194/7b741846-96ba-4b33-b59d-0d7fe45914d4

### CODE REVIEW

**Comment by priyamaggarwal18** [comment]
Great Work! Just do one thing, make the speed of animation fast also instead of red color of line under navlinks make them white.

Also make fade in of buttons from bottom. Like you did from left for (Play Store and App Store).

After doing so, attach the video of your work.

**Comment by kshitizvardhan** [comment]
I will work on these changes and provide update to this pull request.

**Comment by priyamaggarwal18** [comment]
Okay

**Comment by kshitizvardhan** [comment]
## Changes Requested Are Done #7 

- Animations Made faster
- Fade in Buttons from Bottom
- White Line under NavLinks on hovering.

### Here is the Video of the work Attached.


https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/143323194/b7c3d769-e677-4da2-ac60-19c4c6756b20

**Pull request merged**
